apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-standard-lrs
  resources:
    requests:
      storage: 100Gi